test:
	gcc mainFrame.c -o test -lpthread
mutex:
	gcc mutex.c -o mutex -lpthread
priority:
	gcc priority.c -o priority -lpthread
global:
	gcc global_variables.c -o global -lpthread
sema:
	gcc semaphore.c -o sema -lpthread
